---
name: publish release to pypi.org
on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python setup.py sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
      - with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
